apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{.APP_ID}}"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: "{{.APP_ID}}"
    app.kubernetes.io/created-by: "argocd-previews"
spec:
  # The project the application belongs to
  project: previews
  source:
    # Can point to either a Helm chart repo or a git repo
    repoURL: "https://github.com/{{.REPO}}.git"
    # For Helm, this refers to the chart version
    targetRevision: HEAD
    path: "{{.CHART_PATH}}"
    helm:
      version: v3
      values: |
        image:
          #repository: "{{.IMAGE_REPO}}"
          tag: "{{.IMAGE_TAG}}"
        ingress:
          enabled: true
          className: ""
          annotations: {}
            # kubernetes.io/ingress.class: nginx
            # kubernetes.io/tls-acme: "true"
          hosts:
            - host: "{{.HOST}}"
              paths:
                - path: /
                  pathType: ImplementationSpecific
  destination:
    namespace: "{{.APP_ID}}"
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
