---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/created-by: argocd-previews
    name: demo-pr-0000
  name: demo-pr-0000
  namespace: argocd
spec:
  destination:
    namespace: demo-pr-0000
    server: https://kubernetes.default.svc
  project: previews
  source:
    helm:
      values: |
        ingress:
          enabled: true
        image:
          tag: "stable-alpine"
        ingress:
          host: "demo-pr-0000.0.0.0.0.nip.io"
      version: v3
    path: charts/demo
    repoURL: https://github.com/atrakic/argocd-previews.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
