name: e2e
on:
  # for manually triggered workflows
  workflow_dispatch:
    inputs:
      docker_tag:
        description: "Use tag https://hub.docker.com/_/nginx/tags for the image"
        default: 'latest'
        type: "string"
        required: true

jobs:
  kind-e2e:
    name: e2e-${{ inputs.docker_tag }}
    runs-on: ubuntu-latest
    if: ${{ inputs.docker_tag }}
    #if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install tools
        run: brew bundle

      - name: KinD
        uses: helm/kind-action@v1.5.0
        with:
          install_only: true

      - name: Configure git
        run: |
          git config --global user.name "e2e[bot]"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Run e2e
        run: |
          IMAGE_TAG="${{ inputs.docker_tag }}" GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} make e2e

      - name: Debug failure
        if: failure()
        run: |
          helm list -A
          kubectl get all,cm,sa -A
          kubectl get events --sort-by='.metadata.creationTimestamp' -A
          kubectl logs --all-containers=true
